---
apiVersion: v1
kind: Namespace
metadata:
  name: opni
---
apiVersion: opni.io/v1beta1
kind: PretrainedModel
metadata:
  name: control-plane
  namespace: opni
spec:
  source:
    http:
      url: "https://opni-public.s3.us-east-2.amazonaws.com/pretrain-models/control-plane-model-v0.1.2.zip"
  hyperparameters:
    modelThreshold: "0.6"
    minLogTokens: 4
    isControlPlane: "true"
---
apiVersion: opni.io/v1beta1
kind: OpniCluster
metadata:
  name: cluster
  namespace: opni
spec:
  version: v0.3.1
  deployLogCollector: true
  services:
    gpuController:
      enabled: false  # Set this to true for a a cluster with a GPU
    inference:
      pretrainedModels:
      - name: control-plane
    metrics:
      enabled: false # metrics anomaly detection is currently beta
      prometheus:
        name: prometheus-name #The name of the prometheus resource
        namespace: prometheus-namespace #The namespace the prometheus resource is in
  elastic:
    version: 1.1.0
  s3:
    internal: {}
  nats:
    authMethod: nkey
