---
kind: pipeline
type: docker
name: build-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: build-and-package
    image: docker
    environment: &env
      DAGGER_LOG_FORMAT: "plain"
      DAGGER_CACHE_FROM: type=local,src=/cache
      DAGGER_CACHE_TO: type=local,mode=max,dest=/cache
      DOCKER_USERNAME: "none"
      DOCKER_PASSWORD: "none"
    commands:
      - apk add --no-cache curl
      - curl -sL https://dl.dagger.io/dagger/install.sh | sh
      - bin/dagger do build
    volumes: &volumes
      - name: docker
        path: /var/run/docker.sock
      - name: cache
        path: /cache
  - name: test
    image: docker
    environment:
      <<: *env
    commands:
      - bin/dagger do test
    volumes: *volumes
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - cover.out
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
  - name: publish-dockerhub-tag
    image: docker
    environment:
      <<: *env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      TAG: ${DRONE_TAG}
    commands:
      - bin/dagger do push
    volumes: *volumes
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/tags/*
  - name: publish-dockerhub-main
    image: docker
    environment:
      <<: *env
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      TAG: main
    commands:
      - bin/dagger do push
    volumes: *volumes
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: cache
    host:
      path: /var/lib/docker/volumes/opni-build-cache/_data
