config:
  aws:region: us-east-2
  aws:skipCredentialsValidation: "true"
  aws:skipRequestingAccountId: "true"
  opni:cloud: aws
  opni:cluster:
    nodeGroupDesiredSize: 2
    nodeGroupMaxSize: 3
    nodeGroupMinSize: 2
    nodeInstanceType: t3.xlarge
  opni:imageRepo: rancher/opni
  opni:imageTag: main
  opni:namePrefix: opni-e2e-test
  opni:useLocalCharts: "true"
  opni:zoneID:
    secure: AAABAA+P+GwwFQOEhkVqN4/Gj2XKDOaEgpUJK4kZTDcHGzUwBbmgHnTxw1jtKA==
  pulumi:disable-default-providers:
  - kubernetes
