apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opni-gateway-proxy
resources:
  - namespace.yaml
  - rbac.yaml
  - proxy-deployment.yaml
  - prometheus-agent.yaml
  - service.yaml
