apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: agent
spec:
  image: quay.io/prometheus/prometheus:v2.32.1
  containers:
    - name: prometheus
      args:
        - "--config.file=/etc/prometheus/config_out/prometheus.env.yaml"
        - "--web.enable-lifecycle"
        - "--storage.agent.path=/prometheus"
        - "--enable-feature=agent"
  remoteWrite:
    - url: http://opni-gateway-proxy.opni-gateway-proxy.svc:8080/api/v1/push
  replicas: 1
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  serviceAccountName: prometheus-agent
