apiVersion: apps/v1
kind: Deployment
metadata:
  name: opni-gateway-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opni-gateway-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: opni-gateway-proxy
    spec:
      containers:
        - name: proxy
          image: rancher/opni-gateway
          args:
            - proxy
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: config
              mountPath: /etc/opni-gateway
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
      serviceAccountName: opni-gateway-proxy
      volumes:
        - name: config
          secret:
            secretName: opni-gateway
            items:
              - key: config.yaml
                path: config.yaml
            defaultMode: 256
