apiVersion: v1
kind: Service
metadata:
  name: opni-monitoring-agent
  labels:
    {{- include "opni-monitoring-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "opni-monitoring-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
