# Copy to a file named configmap.yaml with the placeholders filled in.

apiVersion: v1
kind: ConfigMap
metadata:
  name: opni-gateway
data:
  config.yaml: |
    apiVersion: v1beta1
    kind: GatewayConfig
    spec:
      listenAddress: ":8080"
      managementListenAddress: "tcp://0.0.0.0:9090"
      cortex: {}
      authProvider: openid
      certs:
        caCert: /var/run/opni-gateway/certs/ca.crt
        servingCert: /var/run/opni-gateway/certs/tls.crt
        servingKey: /var/run/opni-gateway/certs/tls.key
      storage:
        type: etcd
        etcd:
          endpoints:
            - opni-gateway-etcd:2379
    ---
    apiVersion: v1beta1
    kind: AuthProvider
    metadata:
      name: openid
    spec:
      type: openid
      options:
        jwkUrl: <your-jwk-url-here>
