apiVersion: apps/v1
kind: Deployment
metadata:
  name: opni-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opni-gateway
  template:
    metadata:
      labels:
        app: opni-gateway
    spec:
      containers:
        - name: gateway
          image: rancher/opni-gateway
          args:
            - serve
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9090
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: config
              mountPath: /etc/opni-gateway
            - name: certs
              mountPath: /var/run/opni-gateway/certs
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
      volumes:
        - name: config
          configMap:
            name: opni-gateway
            defaultMode: 256
        - name: certs
          secret:
            secretName: opni-gateway-serving-cert
            defaultMode: 256
      dnsPolicy: ClusterFirst
