apiVersion: v1
kind: Service
metadata:
  name: opni-gateway
  labels:
    app: opni-gateway
spec:
  type: ClusterIP
  selector:
    app: opni-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: management
      port: 9090
      targetPort: management
