enabled: true
image:
  repository: docker.io/grafana/grafana
  tag: main
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Opni
        type: prometheus
        access: proxy
        url: https://opni-monitoring.opni-monitoring.svc:8080/prometheus
        withCredentials: true
        editable: false
        jsonData:
          tlsAuthWithCACert: true
          oauthPassThru: true
grafana.ini:
  server:
    domain: "grafana.{{ .Environment.Values.hostname }}"
    root_url: "grafana.{{ .Environment.Values.hostname }}"
  auth.generic_oauth:
    tls_client_ca: /run/opni-monitoring/certs/ca.crt
extraSecretMounts:
  - name: opni-cacert
    mountPath: /run/opni-monitoring/certs
    readOnly: true
    projected:
      sources:
        - secret:
            name: opni-gateway-serving-cert
            items:
              - key: ca.crt
                path: ca.crt
tls:
  - secretName: grafana-tls-keys
    hosts:
      - "grafana.{{ .Environment.Values.hostname }}"
persistence:
  enabled: true