enabled: true
image:
  repository: docker.io/grafana/grafana
  tag: main
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Opni
        type: prometheus
        access: proxy
        url: https://opni-monitoring.opni-monitoring.svc:8080/prometheus
        withCredentials: true
        editable: false
        jsonData:
          tlsAuthWithCACert: true
          oauthPassThru: true
        secureJsonData:
          tlsCACert: "$__file{/run/opni-monitoring/certs/ca.crt}"
grafana.ini:
  server:
    domain: "grafana.localhost"
    root_url: "grafana.localhost"
  auth.generic_oauth:
    scopes: "openid profile email"
extraSecretMounts:
  - name: opni-cacert
    mountPath: /run/opni-monitoring/certs
    readOnly: true
    projected:
      sources:
        - secret:
            name: opni-gateway-serving-cert
            items:
              - key: ca.crt
                path: ca.crt

tls:
  - secretName: grafana-tls-keys
    hosts:
      - "grafana.localhost"
persistence:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "grafana.localhost"
