global:
  rbac:
    create: false
alertmanager:
  enabled: false
serviceAccount:
  create: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
kube-state-metrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheusOperator:
  enabled: false
prometheus:
  enabled: false
defaultRules:
  create: false
