apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opni-gateway-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opni-gateway-serving-cert
spec:
  secretName: opni-gateway-serving-cert
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    name: opni-gateway-issuer
  dnsNames:
    - "opni-gateway.svc.cluster.local"
