replicaCount: 1

image:
  repository: rancher/opni
  pullPolicy: Always
  tag: "v0.4.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

gateway:
  enabled: false
  # Service type for the external gateway APIs
  serviceType: LoadBalancer
  # Gateway hostname (required if gateway.enabled is true)
  hostname: ""
  # Auth provider config (required if gateway.enabled is true)
  auth: 
    # Noauth provider:
    # provider: noauth

    # Openid provider:
    # provider: openid
    # openid: 
    #   {} # see docs

  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraVolumeMounts: []
