# Copy this to a file named cortex.yaml and edit it with your own values.

config:
  # https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config
  blocks_storage:
    backend: s3
    s3: &s3_config
      # The S3 bucket endpoint. It could be an AWS S3 endpoint listed at
      # https://docs.aws.amazon.com/general/latest/gr/s3.html or the address of an
      # S3-compatible service in hostname:port format.
      endpoint: ""
      # S3 region. If unset, the client will issue a S3 GetBucketLocation API call
      # to autodetect it.
      region: ""
      # S3 access key ID
      access_key_id: ""
      # S3 secret access key
      secret_access_key: ""
      # S3 bucket name
      bucket_name: opni-monitoring-data
  alertmanager_storage:
    backend: s3
    s3:
      <<: *s3_config
      bucket_name: opni-monitoring-alertmanager
  ruler_storage:
    backend: s3
    s3:
      <<: *s3_config
      bucket_name: opni-monitoring-ruler
