# Copy this to a file named grafana.yaml and edit it with your own values.
grafana.ini:
  auth.proxy:
    enabled: true
  auth.basic:
    enabled: false
  auth.generic_oauth:
    enabled: true
    client-id: ""
    client-secret: ""
    auth-url: ""
    token-url: ""
    api-url: ""
    allowed-domains: ""
    role-attribute-path: "" # See grafana docs. Example: "contains(resource_access.grafana.roles[*], 'Admin') && 'Admin' || contains(resource_access.grafana.roles[*], 'Editor') && 'Editor' || 'Viewer'"
