
url: local
version: 0.5.4
workingDir: charts
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
    addCRDValidationToMainChart: true