apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-fallback-config
  labels:
    {{- include "opni-monitoring.labels" . | nindent 4 }}
data:
  fallback.yaml: |-
    global: {}
    templates: []
    route:
      receiver: default
    receivers:
      - name: default
    inhibit_rules: []
    mute_time_intervals: []