# opni-gateway-ca [Root CA]
# │
# ├─> opni-gateway-serving-cert [Leaf]
# │
# └─> cortex-intermediate-ca [Intermediate CA]
#     │
#     ├─> cortex-client-ca [Intermediate CA]
#     │   │
#     │   └─> cortex-client-cert [Leaf]
#     │
#     └─> cortex-serving-cert [Leaf]

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: opni-gateway-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opni-gateway-ca
spec:
  isCA: true
  commonName: opni-gateway-ca
  secretName: opni-gateway-ca-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: opni-gateway-selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opni-gateway-ca-issuer
spec:
  ca:
    secretName: opni-gateway-ca-keys
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opni-gateway-serving-cert
spec:
  secretName: opni-gateway-serving-cert
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: opni-gateway-ca-issuer
  dnsNames:
    - opni-monitoring.opni-monitoring.svc
    - opni-monitoring.opni-monitoring.svc.cluster.local
{{- if .Values.gateway.dnsNames }}
{{- range .Values.gateway.dnsNames }}
    - {{ . }}
{{- end }}
{{- end }}
{{- if .Values.gateway.ipAddresses }}
  ipAddresses:
{{- range .Values.gateway.ipAddresses }}
    - {{ . }}
{{- end }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cortex-intermediate-ca
spec:
  isCA: true
  secretName: cortex-intermediate-ca-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  dnsNames:
    - cortex-intermediate-ca
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: opni-gateway-ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cortex-intermediate-ca-issuer
spec:
  ca:
    secretName: cortex-intermediate-ca-keys
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cortex-client-ca
spec:
  isCA: true
  secretName: cortex-client-ca-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: cortex-intermediate-ca-issuer
  dnsNames:
    - cortex-client-ca
  usages:
    - digital signature
    - key encipherment
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cortex-client-ca-issuer
spec:
  ca:
    secretName: cortex-client-ca-keys
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cortex-client-cert
spec:
  secretName: cortex-client-cert-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    name: cortex-client-ca-issuer
  dnsNames:
    - cortex-client
  usages:
    - digital signature
    - key encipherment
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cortex-serving-cert
spec:
  secretName: cortex-serving-cert-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: cortex-intermediate-ca-issuer
  dnsNames:
    - cortex-server
    - cortex-alertmanager
    - cortex-alertmanager-headless
    - cortex-compactor
    - cortex-distributor
    - cortex-distributor-headless
    - cortex-ingester
    - cortex-ingester-headless
    - cortex-querier
    - cortex-query-frontend
    - cortex-query-frontend-headless
    - cortex-ruler
    - cortex-store-gateway
    - cortex-store-gateway-headless

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-intermediate-ca
spec:
  isCA: true
  secretName: etcd-intermediate-ca-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  dnsNames:
    - etcd-intermediate-ca
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: opni-gateway-ca-issuer
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd-intermediate-ca-issuer
spec:
  ca:
    secretName: etcd-intermediate-ca-keys
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client-cert
spec:
  commonName: root # etcd user
  secretName: etcd-client-cert-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    name: etcd-intermediate-ca-issuer
  dnsNames:
    - root
  usages:
    - digital signature
    - key encipherment
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-serving-cert
spec:
  commonName: root # etcd user
  secretName: etcd-serving-cert-keys
  privateKey:
    algorithm: Ed25519
    encoding: PKCS1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: etcd-intermediate-ca-issuer
  dnsNames:
    - etcd
    - etcd.opni-monitoring.svc.cluster.local
    - etcd.opni-monitoring.svc
    - "*.etcd-headless.opni-monitoring.svc.cluster.local"
    - "*.etcd-headless.opni-monitoring.svc"
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth