apiVersion: v1
kind: Service
metadata:
  name: {{ include "opni-monitoring.fullname" . }}
  labels:
    {{- include "opni-monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- if hasPrefix "tcp://" .Values.management.grpcListenAddress }}
    - name: management
{{- $a := split ":" .Values.management.grpcListenAddress }}
      port: {{ $a._2 }}
      targetPort: management-grpc
      protocol: TCP
{{- end }}
{{- if .Values.management.httpListenAddress }}
    - name: management-http
{{- $a := split ":" .Values.management.httpListenAddress }}
      port: {{ $a._1 }}
      targetPort: management-http
      protocol: TCP
{{- end }}
{{- if .Values.management.webListenAddress }}
    - name: management-web
{{- $a := split ":" .Values.management.webListenAddress }}
      port: {{ $a._1 }}
      targetPort: management-web
      protocol: TCP
{{- end }}
{{- if eq .Values.auth.provider "noauth" }}
    - name: noauth
      port: {{ .Values.auth.noauth.port }}
      targetPort: noauth
      protocol: TCP
{{- end }}
  selector:
    {{- include "opni-monitoring.selectorLabels" . | nindent 4 }}
