name: Build
on:
  push:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/build.yaml"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/build.yaml"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go Module Cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/go
          key: cache-go-${{ runner.os }}-${{ github.sha }}
          restore-keys: cache-go-${{ runner.os }}-
      - name: Test Binary Cache
        uses: actions/cache@v2.1.7
        with:
          path: /home/runner/work/opni-monitoring/opni-monitoring/testbin
          key: cache-testbin-${{ runner.os }}-${{ github.sha }}
          restore-keys: cache-testbin-${{ runner.os }}-
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go run github.com/magefile/mage
      - name: Test
        run: go run github.com/magefile/mage test
      - name: Upload Results To Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./cover.out
