name: Build
on:
  push:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/build.yaml"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/build.yaml"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go
          restore-keys: |
            ${{ runner.os }}-go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
      - name: Install dependencies
        run: go install github.com/magefile/mage@latest
      - name: Build
        run: mage
      - name: Test
        run: mage test
      - name: Upload Results To Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./cover.out
          verbose: true # optional (default = false)
